Repository cerner/terra-application, pull requests merged in 2023-08, with the labels that each got.

#344 Add CI-CD to terra-application-v1 branch
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/setup/action.yml
  .github/workflows/ci-cd.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-preview.yml
  .travis.yml
  dangerfile.js
  package.json
Labels: terra-application-v1

#345 [Terra-Dev-Site] Reverts MDX version from V2 to V1
  packages/terra-application-docs/CHANGELOG.md
  packages/terra-application-docs/src/terra-dev-site/test/terra-dev-site/markdownCheatSheet.test.mdx
  packages/terra-application-docs/src/terra-dev-site/test/terra-dev-site/mdxMarkdown/Links.test.mdx
  packages/terra-application-docs/src/terra-dev-site/tool/terra-dev-site/UpgradeGuides.f/v6.0.0.t.tool.mdx
  packages/terra-application/CHANGELOG.md
  packages/terra-application/src/terra-dev-site/app/components.2/ApplicationBase.app.mdx
  packages/terra-dev-site/CHANGELOG.md
  packages/terra-dev-site/package.json
  packages/terra-dev-site/src/webpack/plugin/siteLoaderUtils.js
  packages/terra-dev-site/tests/jest/webpack/plugin/__snapshots__/SitePlugin.test.js.snap
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/loaders-spec/props_table.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/inline_syntax.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md_emphasis.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md_inline_html.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md_links.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md_tables.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/mdx-spec/inline_syntax.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/mdx-spec/md_emphasis.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/mdx-spec/md_inline_html.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/mdx-spec/md_links.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/mdx-spec/md_tables.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/mdx-spec/mdx.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/props_table.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/inline_syntax.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md_emphasis.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md_inline_html.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md_links.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md_tables.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/mdx-spec/inline_syntax.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/mdx-spec/md_emphasis.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/mdx-spec/md_inline_html.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/mdx-spec/md_links.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/mdx-spec/md_tables.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/mdx-spec/mdx.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/loaders-spec/props_table.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/marked-spec/inline_syntax.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/marked-spec/md.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/marked-spec/md_emphasis.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/marked-spec/md_inline_html.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/marked-spec/md_links.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/marked-spec/md_tables.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/mdx-spec/inline_syntax.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/mdx-spec/md_emphasis.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/mdx-spec/md_inline_html.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/mdx-spec/md_links.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/mdx-spec/md_tables.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/mdx-spec/mdx.png
  packages/terra-dev-site/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_tiny/singlePage-spec/checks_a11y.png
Labels: terra-dev-site-v7

#348 Release Aug 22
  packages/terra-application-docs/CHANGELOG.md
  packages/terra-application-docs/package.json
  packages/terra-application/CHANGELOG.md
  packages/terra-application/package.json
  packages/terra-dev-site/CHANGELOG.md
  packages/terra-dev-site/package.json
Labels: release

#347 Upgrade NPM to v9
  .github/actions/setup/action.yml
  .npmrc
  package.json
Labels: terra-application-v1

#346 Upgrade NPM to v9
  .github/actions/setup/action.yml
  .npmrc
  package.json
Labels: terra-application-v2

#350 Update uuid mock to spyOn for v1
  packages/terra-application/CHANGELOG.md
  packages/terra-application/package.json
  packages/terra-application/src/application-loading-overlay/ApplicationLoadingOverlay.jsx
  packages/terra-application/src/application-navigation/ApplicationNavigation.jsx
  packages/terra-application/src/application-status-overlay/ApplicationStatusOverlay.jsx
  packages/terra-application/src/notification-banner/NotificationBanner.jsx
  packages/terra-application/src/utils/scroll-persistence/scroll-persistence.js
  packages/terra-application/tests/jest/application-loading-overlay/ApplicationLoadingOverlay.test.jsx
  packages/terra-application/tests/jest/application-status-overlay/ApplicationStatusOverlay.test.jsx
  packages/terra-application/tests/jest/utils/scroll-persistence/scroll-persistence.test.js
  packages/terra-dev-site/CHANGELOG.md
  packages/terra-dev-site/package.json
  packages/terra-dev-site/src/utils/scroll-persistence/scroll-persistence.js
Labels: terra-application-v1

#349 jest.mock replaced with spyOn
  packages/terra-application/CHANGELOG.md
  packages/terra-application/package.json
  packages/terra-application/tests/jest/application-loading-overlay/ApplicationLoadingOverlay.test.jsx
  packages/terra-application/tests/jest/application-status-overlay/ApplicationStatusOverlay.test.jsx
  packages/terra-application/tests/jest/utils/scroll-persistence/scroll-persistence.test.js
  packages/terra-dev-site/CHANGELOG.md
  packages/terra-dev-site/package.json
Labels: terra-application-v2
